/** Generated by YAKINDU Statechart Tools code generator. */
package fr.univcotedazur.polytech.si4.fsm.stopwatch.v0.defaultsm;

import fr.univcotedazur.polytech.si4.fsm.stopwatch.v0.IStatemachine;
import fr.univcotedazur.polytech.si4.fsm.stopwatch.v0.ITimerCallback;
import java.util.LinkedList;
import java.util.List;
import java.util.Queue;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;

public interface IDefaultSMStatemachine extends ITimerCallback,IStatemachine {
	public interface SCInterface {
	
		public void raiseLeftB();
		
		public void raiseRightB();
		
		public void raiseMiddleB();
		
		public void raiseRecodeB();
		
		public boolean isRaisedDoStart();
		
		public boolean isRaisedDoStop();
		
		public boolean isRaisedDoPause();
		
		public boolean isRaisedInit();
		
		public boolean isRaisedShowTime();
		
		public boolean isRaisedShowDate();
		
		public boolean isRaisedRecodeTime();
		
		public boolean isRaisedDoReset();
		
	public List<SCInterfaceListener> getListeners();
	}
	
	public interface SCInterfaceListener {
	
		public void onDoStartRaised();
		public void onDoStopRaised();
		public void onDoPauseRaised();
		public void onInitRaised();
		public void onShowTimeRaised();
		public void onShowDateRaised();
		public void onRecodeTimeRaised();
		public void onDoResetRaised();
		}
	
	public SCInterface getSCInterface();
	
}
